language: java
jdk:
  - oraclejdk8
install: true
script: gradle dist
deploy:
  provider: releases
  api_key:
    secure: "ClQo5CEbMG5aKSozgBIkyiq8OgtdyA7w+mECyvbIx4Dnr5wTO3Xir/yPWunutxcL+H5JzuZFR1cNX1wpftgmdSI8Ptr2WCcBQz68juIaMyhDxfz6X7B+fqFz2/5/wBp5azVvzUugqX+rbt3/vU1kQjbkCxttCdOYA6DYsID8ZAldm26ZdXvoU971JJtTJl9GalAFoMg9Z2qTJ21Hl3T4rX2FfUxdkD/GbwdWnkA42817cqMjOzdy5qdw5D+D6IHu6RRZ0aPSFyxROIrxF7axO/qUAwBh+nmVN1OsMPRGOACbIsFK4K9TG30Yn8E18Y4Wz8zOFahaYIGxbK1pOaCX9v8df85qUjpmvy/Omv8Qb9N3csZ34vjX7UA1dE5N5yLJh+oLib/7SgKR52/7BIdc+/6XLlItBhtcE+nl4mDD/SbWz6HjCKTCkDt7xbfrQJUrYCrjiYHOfLAfhjOokr6I/BcyMVy0pEh/+7sFl9mtNdFyBPqIlPegUO8OQryCPAqNq1G//MfZWf6sodHujSPwWbsM/n4cA48/eYLdOhFYIdLOMSJlP3lYHRB1+YboGlxEyTzv2sgEAOsQ5ThT1mTvdT0eP/qh4YEWWUqxixJdw6iD52zsKXJoODL3+xJ43kRjaOiDz1Bs6+H5QN/IQ+VAjbFPIMtWNfsro+CqZ0Wv2p0="  
  skip_cleanup: true
  file_glob: true
  file:
    - dist/*.zip
  on:
    tags: true
notifications:
  email:
  - rwdalpe@gmail.com